version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: "/apps/web"
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: "/tools/ingest"
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: "/tools/tldr"
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: "/tools/lint"
    schedule: { interval: weekly }
